---
title: What is the Central Limit Theorem, actually?
author: Steph and John
date: '2019-03-16'
slug: what-is-the-central-limit-theorem-actually
categories:
  - Frequentist
tags:
  - Why
---

The Central Limit Theorem underpins alot of statistics and modelling. Once you understand it, what it does and what it _doesn't_, critically evaluating the models and methods you use becomes easier.

## When do people use them, it's just a theory, right?

First let's start with a couple of situations where you may be using the central limit theorem without even knowing it:

    * Have you ever done any A/B testing? Have you ever tested the hypothesis that two means, proportions or variances are equal? These tests typically use the CLT to achieve the results they depend on.
    * Have you ever run a regression model of some kind? A generalised linear model? Logistic regression? Our understanding of how these models are acting - our understanding of the uncertainty these models are able to mitigate- is based on the CLT.
    * What about ensemble or model averaging methods? Guess which 'trick' they're using?
    * Confidence intrvals? Yep, those too.

## What _isn't_ the central limit theorem?

The most common misperception we hear is the idea that _"when sample sizes get big, all distributions go to normal."_ Put simply, if this was the case most statisticians could all take up new hobbies. We'll show you why this isn't the case.

## So what _is_ the central limit theorem.

So it's central limit theorems all the way down. That's right, _Central Limit Theorems_. There's a whole collection of them, each relating to a similar but slightly different situation.

We'll concentrate on the version I call _classic_ but is actually the [Lindeberg-Levy Central Limit Theorem](https://en.wikipedia.org/wiki/Central_limit_theorem).




    
