---
title: "Too big to fail"
author: "Steph and John"
date: '2019-03-17'
slug: p-values
tags: p-values
categories:
- Bayes
- Frequentist
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intro Banter

__John__: Where do you want to start Steph?

__Steph__: I don't know John. How about we start with something that everyone 
reading this is probably familiar with? Did you want to do some $p$-value bashing?

__John__: Yeah, there are some Bayesians out there who refuse to do hypothesis
testing on principal.

__Steph__: There is a lot of talk about reproducibility, replicability, robustness,
and practices that lead to finding "truth" in the context of scientific practice. 
These issues also com
It might be a good place to start.

__John__: So what do you think

__John__: So a few years ago my wife was rear-ended while driving and the
car was written off so we needed to buy a new car. While we were looking to
get a new car my sister in law asked is (as a joke) "Are you getting a red car?
I heard their fast!"

# Case 1: Extra Sensory Perception

We now consider a second example described by Sprenger (2013).

__Sprenger's example:__ Jahn (1987) used electronic and quantum-mechanical 
random event generators with visual feedback; the subject with alleged 
psychokinetic ability tries to "influence" the generator. The number of 
"successes" in this experiment was $s=52,263,470$ and the number of trials 
was $n=104,490,000$.

Assuming independence of each trial we have
$$
x_i|\rho \sim \mbox{Bernoulli}(\rho), 
$$

where $1\le i\le n$ with $p\in[0,1]$.

If we perform the test
$$
H_0\colon \rho=0.5 \qquad \mbox{versus} \qquad H_1\colon \rho\ne 0.5,
$$

then a rejection of $H_0$ leads to evidence that the subject has psychokinetic 
ability. Using the data a classical hypothesis testing approach leads to a 
$p$-value approximately equal to $0.0003$, leading to a rejection of the null 
hypothesis for the $\alpha=0.05$ cut-off. A 95\% confidence interval for $\rho$ 
is $(0.50008, 0.50027)$.

# Case 2: The Large Hadron Collider

# Closing Banter



 